#gcloud builds submit --config=cloudbuild.yaml --substitutions=_REGION_NAME="europe-west1",_BUCKET="this-is-my-bucket"

steps:
# Check out latest from master
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/inhouse-nav/r/cloudrunfunction']
# Build fulfillment java-akka-http server for action-on-google dialogflow...pfff that's long
- name: 'gcr.io/cloud-builders/gradle'
  args: ['build']
  dir: 'cloudrun'
# Build gcp cloudrun image with the fulfillment java server
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/cloudrunfunction', '-f', 'Dockerfile', './']
  dir: 'cloudrun'
# Push to private registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloudrunfunction']
# Deploy the fulfillment server on gcp cloudrun: gcloud beta run deploy inhouse-webhook --image gcr.io/[PROJECT-ID]/dialogflowcloudrun \
#      --set-env-vars="JAVA_TOOL_OPTIONS=-XX:MaxRAM=256m"
# see https://cloud.google.com/sdk/gcloud/reference/beta/run/deploy
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'inhouse-webhook', '--image', 'gcr.io/$PROJECT_ID/cloudrunfunction', '--region=${_REGION_NAME}', '--set-env-vars="JAVA_TOOL_OPTIONS=-XX:MaxRAM=256m"']

substitutions:
  #_BUCKET: this-is-my-bucket
  _REGION_NAME: #region to deploy project

timeout: 1200s
images: ['gcr.io/$PROJECT_ID/cloudrunfunction']
