# Stage 1: Build the native image
FROM oracle/graalvm-ce:1.0.0-rc15 as graalvm
COPY build/libs/dialogflow-cloudrun-0.1.0.jar /home/app/1.0.0-rc15
WORKDIR /home/app
RUN native-image --no-server -cp 1.0.0-rc15

# Stage 3: Prepare Server
FROM frolvlad/alpine-glibc
EXPOSE 8080
COPY --from=graalvm /home/app/dialogflow-cloudrun.jar .
ENTRYPOINT ["./dialogflow-cloudrun.jar"]
